FROM node:24

# Directorio de trabajo
WORKDIR /app

# Copiar solo package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm i -D -E vite
RUN npm install -g @ionic/cli
RUN npm install

# Exponer puerto de Ionic
EXPOSE 8100

# Comando para desarrollo con hot reload
CMD ["ionic", "serve", "--host", "0.0.0.0", "--port", "8100", "--external"]
